version: '3.7'

services:
  mysql:
    image: mysql
    ports:
      - "9025:3306"
      - "33060:33060"
    container_name: quantumservicefilesystemdb
    hostname: quantumservicefilesystemdb
    networks:
      - quantumservicefilesystemnetwork
    volumes:
      - !!!{yourLocalFolder}!!!:/var/lib/mysql
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.7
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.16-2debian9
      - MYSQL_ROOT_PASSWORD=root

  mqseries:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: quantumservicefilesystemmq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    container_name: quantumservicefilesystemmq
    stdin_open: true
    tty: true
    restart: always
    networks:
      - quantumservicefilesystemnetwork

networks:
  quantumservicefilesystemnetwork:
    name: quantumservicefilesystemnetwork
