spring:
  application:
    name: QuantumService
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

ibmq:
  apiHost: https://api.quantum-computing.ibm.com/v2
  apiToken: ${IBMQ_API_TOKEN}

server:
  port: 9005
