server:
  port: ${SERVER_PORT:9005}

spring:
  application:
    name: QuantumServiceMessaging
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

ibmq:
  apiHost: https://api.quantum-computing.ibm.com/v2
  apiToken: ${IBMQ_API_TOKEN}
