spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quantum_service_messaging?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    user: admin
    password: passw0rd
    conn-name: localhost(1414)
